logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  rabbitmq:
    host: 192.168.18.100
    port: 5672
    username: power
    password: 123456
    virtual-host: /
    listener:
      simple:
        prefetch: 1 # 每次只能得到一条消息，处理完成ACK之后，才能获取下一条消息